services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6371:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=space-dominos'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5431:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres:

